name: pub_crawl
description: Crawls, fetches and queries published pub packages.
version: 0.0.1
homepage: https://github.com/pq/pub_crawl

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  cli_util: ^0.1.3
  linter: ^0.1.82
  pool: ^1.4.0

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0

# Update to point to your local linter source for lint rule testing.
#dependency_overrides:
#  linter:
#    path:
#      ../linter
